"""
Investigation and AI Pydantic schemas.

Defines request/response contracts for the Phase 3 AI investigation engine.
"""

from typing import List, Optional
from pydantic import BaseModel, ConfigDict, Field


class RootCause(BaseModel):
    """Diagnosed root cause with explanation and confidence."""

    model_config = ConfigDict(from_attributes=True)

    cause: str = Field(..., description="Short title of the identified root cause")
    explanation: str = Field(..., description="Evidence-backed technical explanation")
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence score between 0.0 and 1.0",
    )


class Evidence(BaseModel):
    """Concrete log evidence extracted during investigation."""

    model_config = ConfigDict(from_attributes=True)

    source: str = Field(..., description="Origin of evidence (step name, job name, or log file)")
    detail: str = Field(..., description="Relevant error message or log line extract")
    importance: str = Field(
        default="high",
        description="Importance rating: high, medium, or low",
    )


class SuggestedFix(BaseModel):
    """Technical recommendation to resolve the failure."""

    model_config = ConfigDict(from_attributes=True)

    description: str = Field(..., description="Concrete suggested fix action")
    reason: str = Field(..., description="Rationale for why this fix resolves the issue")


class InvestigationRequest(BaseModel):
    """Payload to trigger an AI investigation for a workflow run."""

    owner: str = Field(..., min_length=1, description="GitHub repository owner/organization")
    repo: str = Field(..., min_length=1, description="GitHub repository name")
    run_id: int = Field(..., gt=0, description="GitHub Actions workflow run ID")


class InvestigationResponse(BaseModel):
    """Complete structured diagnostic report generated by the AI investigation engine."""

    model_config = ConfigDict(from_attributes=True)

    investigation_id: str = Field(..., description="Unique investigation identifier")
    repository: str = Field(..., description="Full repository name (owner/repo)")
    workflow_run_id: int = Field(..., description="Target GitHub Actions workflow run ID")
    workflow_name: str = Field(..., description="Name of the workflow")
    status: str = Field(
        ...,
        description="Status of the investigation (completed, not_required, failed)",
    )
    summary: str = Field(..., description="Concise executive diagnosis summary")
    root_causes: List[RootCause] = Field(
        default_factory=list,
        description="Identified root causes with confidence ratings",
    )
    evidence: List[Evidence] = Field(
        default_factory=list,
        description="Supporting evidence extracted from pipeline logs",
    )
    affected_components: List[str] = Field(
        default_factory=list,
        description="List of systems, packages, or services affected",
    )
    severity: str = Field(
        default="medium",
        description="Failure severity: critical, high, medium, or low",
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Overall diagnosis confidence score between 0.0 and 1.0",
    )
    suggested_fixes: List[SuggestedFix] = Field(
        default_factory=list,
        description="Actionable suggested fixes for engineer review",
    )
    validation_steps: List[str] = Field(
        default_factory=list,
        description="Recommended validation checks before re-running",
    )
    model: str = Field(..., description="AI model used for analysis")
    provider: str = Field(default="omniroute", description="AI provider abstraction name")
    created_at: str = Field(..., description="ISO 8601 timestamp of investigation creation")
    error: Optional[str] = Field(
        None,
        description="Error detail if investigation encountered a provider/processing issue",
    )


class InvestigationListItem(BaseModel):
    """Summary record for listing historical investigations."""

    model_config = ConfigDict(from_attributes=True)

    investigation_id: str
    repository: str
    workflow_run_id: int
    workflow_name: str
    status: str
    summary: str
    severity: str
    confidence: float
    model: str
    provider: str
    created_at: str


class AIStatusResponse(BaseModel):
    """Health and configuration status of the AI provider."""

    model_config = ConfigDict(from_attributes=True)

    configured: bool = Field(..., description="Whether AI provider configuration is present")
    available: bool = Field(..., description="Whether AI provider endpoint is reachable")
    provider: str = Field("omniroute", description="Name of the AI provider")
    model: str = Field(..., description="Configured model identifier")


class InvestigationErrorDetail(BaseModel):
    """Error payload returned when investigation requests fail."""

    code: str
    message: str
    details: Optional[dict] = None


class InvestigationErrorResponse(BaseModel):
    """Error response envelope."""

    detail: InvestigationErrorDetail
